ChatbotAdmin/Controllers/AccommodationController.cs
using ChatbotAdmin.Models;
using ChatbotAdmin.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChatbotAdmin.Controllers
{
    public class AccommodationController : Controller
    {
        private readonly IAccommodationRepository _accommodationRepository;
        private readonly ILogger<AccommodationController> _logger;
        private readonly List<string> accommodationType = new() { "off-campus", "on-campus" };

        public AccommodationController(IAccommodationRepository accommodationRepository, ILogger<AccommodationController> logger)
        {
            _accommodationRepository = accommodationRepository;
            _logger = logger;
        }
        // GET: AccommodationController
        public ActionResult Index()
        {
            try
            {
                var accommodations = _accommodationRepository.GetAccommodations();
                return View(accommodations.OrderByDescending(v=>v.Id).ToList());
            }
            catch (Exception ex)
            {
                _logger.LogError("error fetching accommodations", ex);
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: AccommodationController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var accommodation = _accommodationRepository.GetAccommodations(id);
                if (accommodation != null)
                {
                    return View(accommodation);
                }
                _logger.LogInformation("accommodation not found using id {}", id);
            }
            catch (Exception ex)
            {
                _logger.LogError("error fetching accommodations with id", ex);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: AccommodationController/Create
        public ActionResult Create()
        {
            ViewBag.AccommodationType = accommodationType;
            return View();
        }

        // POST: AccommodationController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Accommodation accommodation)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var newAccommodation = _accommodationRepository.SaveAccommodation(accommodation);
                    if (newAccommodation.Id> 0)
                    {
                        return RedirectToAction(nameof(Details), newAccommodation.Id);                        
                    }
                    ModelState.AddModelError("", "unable to save accommodation now, try again later.");
                }
            }
            catch(Exception ex)
            {
                _logger.LogError("unable to create accommodation", ex);
                ModelState.AddModelError("", "error occured: " + ex.Message);
            }
            ViewBag.AccommodationType = accommodationType;
            return View(accommodation);
        }

        // GET: AccommodationController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                _logger.LogInformation("about to update accommodation");
                var accommodation = _accommodationRepository.GetAccommodations(id);
                if (accommodation != null)
                {
                    ViewBag.AccommodationType = accommodationType;
                    return View(accommodation);
                }
                _logger.LogInformation("accommodation not found using id {}", id);
            }
            catch (Exception ex)
            {
                _logger.LogError("error fetching accommodations with id", ex);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: AccommodationController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Accommodation accommodation)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var updated = _accommodationRepository.UpdateAccommodation(accommodation);
                    if (updated)
                    {
                        return RedirectToAction(nameof(Details), accommodation.Id);                       
                    }
                    ModelState.AddModelError("", "unable to update accommodation now, try again later.");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("unable to updae accommodation", ex);
                ModelState.AddModelError("", "error occured: " + ex.Message);
            }
            ViewBag.AccommodationType = accommodationType;
            return View(accommodation);
        }
        
    }
}

ChatbotAdmin/Controllers/CourseController.cs
using ChatbotAdmin.Models;
using ChatbotAdmin.Repository;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ChatbotAdmin.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepository _courseRepository;
        private readonly ILogger<AccommodationController> _logger;
        private readonly List<string> courseLevel = new() { "postgraduate", "undergraduate" };

        public CourseController(ICourseRepository courseRepository, ILogger<AccommodationController> logger)
        {
            _courseRepository = courseRepository;
            _logger = logger;
        }
        // GET: CourseController
        public ActionResult Index()
        {
            try
            {
                var courses = _courseRepository.GetCourses();
                return View(courses.OrderByDescending(v=>v.Id).ToList());
            }
            catch (Exception ex)
            {
                _logger.LogError("error fetching courses", ex);
            }
            return RedirectToAction("Index", "Home");
        }

        // GET: CourseController/Details/5
        public ActionResult Details(int id)
        {
            try
            {
                var course = _courseRepository.GetCourses(id);
                if (course != null)
                {
                    return View(course);
                }
                _logger.LogInformation("course not found using id {}", id);
            }
            catch (Exception ex)
            {
                _logger.LogError("error fetching course with id", ex);
            }
            return RedirectToAction(nameof(Index));
        }

        // GET: CourseController/Create
        public ActionResult Create()
        {
            ViewBag.Level = courseLevel;
            return View();
        }

        // POST: CourseController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Course course)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var newCourse = _courseRepository.SaveCourse(course);
                    if (newCourse.Id > 0)
                    {
                        return RedirectToAction(nameof(Details), newCourse.Id);
                    }
                    ModelState.AddModelError("", "unable to save course now, try again later.");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("unable to create course", ex);
                ModelState.AddModelError("", "error occured: " + ex.Message);
            }
            ViewBag.Level = courseLevel;
            return View(course);
        }

        // GET: CourseController/Edit/5
        public ActionResult Edit(int id)
        {
            try
            {
                _logger.LogInformation("about to update course");
                var course = _courseRepository.GetCourses(id);
                if (course != null)
                {
                    ViewBag.Level = courseLevel;
                    return View(course);
                }
                _logger.LogInformation("course not found using id {}", id);
            }
            catch (Exception ex)
            {
                _logger.LogError("error fetching course with id", ex);
            }
            return RedirectToAction(nameof(Index));
        }

        // POST: CourseController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Course course)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    var updated = _courseRepository.UpdateCourse(course);
                    if (updated)
                    {
                        return RedirectToAction(nameof(Details), course.Id);
                    }
                    ModelState.AddModelError("", "unable to update curse now, try again later.");
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("unable to updae course", ex);
                ModelState.AddModelError("", "error occured: " + ex.Message);
            }
            ViewBag.Level = courseLevel;
            return View(course);
        }        
    }
}

ChatbotAdmin/Controllers/InboxController.cs
using ChatbotAdmin.Models;
using ChatbotAdmin.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;

namespace ChatbotAdmin.Controllers
{
    [Authorize()]
    public class InboxController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MessageService _messageService;

        public InboxController(ILogger<HomeController> logger, MessageService messageService)
        {
            _logger = logger;
            _messageService = messageService;
        }
        // GET: ClubController1
        public ActionResult Index()
        {
            //get inbox
            //var userId = Int32.Parse( Request.HttpContext.User.Claims.First(c => c.Type == ClaimTypes.NameIdentifier).Value.Trim());

            var inboxMessage = _messageService.GetInboxMessages();
            inboxMessage.ForEach(item => {
                if (item.Content.Length>40)
                {
                    item.Content = item.Content.Substring(0, 40) + " ...";
                }
            });
            return View(inboxMessage);

        }

        
        public ActionResult MessageDetails( long id)
        {
            try
            {
                var message = _messageService.GetInboxMessage(id);
                    return View(message);
                
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                _logger.LogError("Error create event controller {}", ex);
            }   
            return RedirectToAction(nameof(Index));
        }

        public ActionResult ReplyChat (long id)
        {
            try
            {
                var message = _messageService.GetInboxMessage(id);
                if (message != null)
                {
                    OutboxMessage outbox = OutboxMessage.InstanceOf(message);

                    return View(outbox);
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("error replying message {}", ex);
            }
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public ActionResult ReplyChat(OutboxMessage message)
        {           
            try
            {
                if (ModelState.IsValid)
                {
                    var replied = _messageService.ReplyChat(message);
                    if (replied)
                    {
                        ViewData["Info"] = "Event created successfully";
                        return RedirectToAction(nameof(Index));
                    }
                    ModelState.AddModelError("", "Unable to create event.");
                }
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
            }
            return View(message);
        }


        [HttpPost]
        public ActionResult DeleteInboxMessage(long id)
        {
            try
            {
                var message = _messageService.GetInboxMessage(id);
                if (message != null)
                {
                    _messageService.DeleteMessageFromInbox(message.Id);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("error deleting inbox message {}", ex);
            }
            return RedirectToAction(nameof(Index));
        }
        
    }
}

ChatbotAdmin/Controllers/OutboxController.cs
using ChatbotAdmin.Models;
using ChatbotAdmin.Models.ViewModel;
using ChatbotAdmin.Repository;
using ChatbotAdmin.Services;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ChatbotAdmin.Controllers
{
    [Authorize()]
    public class OutboxController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly MessageService _messageService;

        public OutboxController(ILogger<HomeController> logger, MessageService messageService)
        {
            _logger = logger;
            _messageService = messageService;
        }
        // GET: ClubController1
        
        public ActionResult Index()
        {
            //get inbox
            //var userId = Int32.Parse( Request.HttpContext.User.Claims.First(c => c.Type == ClaimTypes.NameIdentifier).Value.Trim());

            var message = _messageService.GetOutboxMessages();
            message.ForEach(item =>
            {                
                if (item.Content.Length>40)
                {
                    item.Content = item.Content.Substring(0, 40) + " ...";
                }
                if (item.ReplyMessage.Length>40)
                {
                    item.ReplyMessage = item.ReplyMessage.Substring(0, 40) + " ...";
                }
                
            });
            return View(message);

        }

        
        public ActionResult MessageDetails( long id)
        {
            try
            {
                var message = _messageService.GetOutboxMessage(id);
                    return View(message);
                
            }
            catch (Exception ex)
            {
                TempData["Error"] = ex.Message;
                _logger.LogError("Error create event controller {}", ex);
            }   
            return RedirectToAction(nameof(Index));
        }

        
        [HttpPost]
        public ActionResult DeleteOutboxMessage(long id)
        {
            try
            {
                var message = _messageService.GetOutboxMessage(id);
                if (message != null)
                {
                    _messageService.DeleteMessageFromOutbox(message.Id);
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (Exception ex)
            {
                _logger.LogError("error deleting outbox message {}", ex);
            }
            return RedirectToAction(nameof(Index));
        }
        
    }
}

ChatbotAdmin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Chatbot Admin</title>
    <!-- Favicon -->
    <link rel="shortcut icon" href="~/img/svg/logo.svg" type="image/x-icon">
    <!-- Custom styles -->
    <link rel="stylesheet" href="~/css/style.css">
    <link rel="stylesheet" href="~/css/style2.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link href="~/lib/bootstrap-datepicker/css/bootstrap-datepicker.css" rel="stylesheet" />

    <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,500,600,700,700i|Montserrat:300,400,500,600,700" rel="stylesheet">



    <!-- Libraries CSS Files -->
    <link href="~/lib/font-awesome/css/font-awesome.min.css" rel="stylesheet">
    <link href="~/lib/animate/animate.min.css" rel="stylesheet">
    <link href="~/lib/ionicons/css/ionicons.min.css" rel="stylesheet">
    <link href="~/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">
    <link href="~/lib/lightbox/css/lightbox.min.css" rel="stylesheet">

    <!-- Main Stylesheet File -->
    <link href="css/style.css" rel="stylesheet">

    <!--==========================
    Header
    ============================-->

    <link rel="apple-touch-icon" sizes="57x57" href="img/favicon/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="img/favicon/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="img/favicon/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="img/favicon/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="img/favicon/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="img/favicon/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="img/favicon/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="img/favicon/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="img/favicon/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192" href="img/favicon/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="img/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="img/favicon/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="img/favicon/favicon-16x16.png">
    <link rel="manifest" href="img/favicon/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
</head>

<body>
    <div class="layer"></div>
    <!-- ! Body -->
    <a class="skip-link sr-only" href="#skip-target">Skip to content</a>
    <div class="page-flex">
        <!-- ! Sidebar -->
        <aside class="sidebar">
            <div class="sidebar-start">
                <div class="sidebar-head">
                    <a href="/" class="logo-wrapper" title="Home">
                        <span class="sr-only">Home</span>
                        <span class="icon logo" aria-hidden="true"></span>
                        <div class="logo-text">
                            <span class="logo-title">Chatbot</span>
                            <span class="logo-subtitle">Administration</span>
                        </div>

                    </a>
                    <button class="sidebar-toggle transparent-btn" title="Menu" type="button">
                        <span class="sr-only">Toggle menu</span>
                        <span class="icon menu-toggle" aria-hidden="true"></span>
                    </button>
                </div>
                <div class="sidebar-body">
                    <ul class="sidebar-body-menu">
                        <li>
                            <a class="active" asp-area="" asp-controller="Home" asp-action="Index"><span class="icon home" aria-hidden="true"></span>Home</a>
                        </li>
                    </ul>
                    <ul class="sidebar-body-menu">

                        <li>
                            <a class="show-cat-btn" href="##">
                                <span class="icon category" aria-hidden="true"></span>Settings
                                <span class="category__btn transparent-btn" title="Open list">
                                    <span class="sr-only">Open list</span>
                                    <span class="icon arrow-down" aria-hidden="true"></span>
                                </span>
                            </a>
                            <ul class="cat-sub-menu">
                                <li>
                                    <a href="#"></a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </aside>
        <div class="main-wrapper">
            <!-- ! Main nav -->
            <nav class="main-nav--bg">
                <div class="container main-nav">

                    @if (Context.User.Identity.IsAuthenticated)
                    {
                        <div class="main-nav-start">
                            <div class="search-wrapper">
                                <span>Welcome: </span> @Context.User.Identity.Name
                            </div>
                        </div>
                        <div class="main-nav-end">
                            <a class="nav-link text-dark" asp-controller="Inbox" asp-action="Index">Inbox</a> |
                            <a class="nav-link text-dark" asp-controller="Outbox" asp-action="Index">Outbox</a> |
                            <a class="nav-link text-dark" asp-controller="Accommodation" asp-action="Index">Accommodation</a> |
                            <a class="nav-link text-dark" asp-controller="Course" asp-action="Index">Courses</a> |
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Register">Register User</a> |
                            <a class="danger" asp-area="" asp-controller="Account" asp-action="Logout">
                                <i data-feather="log-out" aria-hidden="true"></i>
                                <span>Log out</span>
                            </a>
                        </div>
                    }
                    else
                    {
                        <div class="main-nav-start">
                            <div class="search-wrapper">
                                <span>Welcome Quest!</span>
                            </div>
                        </div>
                        <div class="main-nav-end">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">
                                <i data-feather="log-in" aria-hidden="true"></i>
                                <span>Login</span>
                            </a>

                            
                        </div>
                    }


                </div>
            </nav>
            <!-- ! Main -->
            <main class="main users chart-page" id="skip-target">
                <div class="container">

                    @RenderBody()

                </div>
            </main>
            <!-- ! Footer -->
            <footer class="footer">
                <div class="container footer--flex">
                    <div class="footer-start">
                        <p>
                            2022 © Chat Admin
                        </p>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <!-- Chart library -->
    <script src="~/js/chart.min.js"></script>
    <!-- Icons library -->
    <script src="~/js/feather.min.js"></script>
    <!-- Custom scripts -->
    <script src="~/js/script.js" asp-append-version="true"></script>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/bootstrap-datepicker/js/bootstrap-datepicker.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    
    <script src="~/lib/jquery/jquery-migrate.min.js"></script>
    <script src="~/lib/easing/easing.min.js"></script>
    <script src="~/lib/mobile-nav/mobile-nav.js"></script>
    <script src="~/lib/wow/wow.min.js"></script>
    <script src="~/lib/waypoints/waypoints.min.js"></script>
    <script src="~/lib/counterup/counterup.min.js"></script>
    <script src="~/lib/isotope/isotope.pkgd.min.js"></script>
    <script src="~/lib/lightbox/js/lightbox.min.js"></script>
    


    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>